
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Json } from './types';

const SUPABASE_URL = "https://bkhuqrzqbexmgpqbyiir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraHVxcnpxYmV4bWdwcWJ5aWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDk2OTcsImV4cCI6MjA1ODA4NTY5N30.BjVmX_zVq0kcRjFA1rBBgdZm3jp6kt_0N3AisXDS5FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Enums exported for use in the application
export type SourceType = 'shopify' | 'amazon' | 'ebay' | 'etsy' | 'woocommerce';
export type QueryType = 'product' | 'order' | 'customer' | 'inventory' | 'collection' | 'custom';
export type ConnectionStatus = 'connected' | 'disconnected' | 'error';

// Helper types for source data
export interface Source {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  type: SourceType;
  store_name: string | null;
  access_token: string | null;
  api_version: string | null;
  client_id: string | null;
  connection_status: ConnectionStatus;
  last_connected_at: string | null;
  connection_error: string | null;
  metadata: Record<string, any> | null;
  created_at: string;
  updated_at: string;
}

// Helper types for API schema data
export interface ApiSchema {
  id: string;
  source_id: string;
  api_version: string;
  schema: Record<string, any>;
  schema_hash: string;
  cache_valid_until: string;
  created_at: string;
  updated_at: string;
}

// Helper types for dataset data
export interface Dataset {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  source_id: string;
  query_type: QueryType;
  query_name: string;
  query_details: Record<string, any> | Json | null;  // Updated to accept Json type
  data: Record<string, any> | Json | null;  // Updated to accept Json type
  data_updated_at: string | null;
  status: string;
  error_message: string | null;
  last_run_duration: number | null;
  record_count: number | null;
  refresh_frequency: string | null;
  next_scheduled_run: string | null;
  last_completed_run: string | null;
  created_at: string;
  updated_at: string;
}
